### ISSUE TITLE
Possible to change license to LGPL3?

### ISSUE THREAD

**Issue by ex-nerd** [zerwes/hiyapyco#15]
IANAL but...

As it stands, any software that includes this library will be forced to be GPL3, which makes it incompatible with many standard python libraries (usually non-copyleft licenses like MIT or BSD), and certainly unusable by any company that might want to benefit from it.

LGPL would keep this specific code copyleft but allow the library to be linked by other code bases without compromising those licenses.

**Comment by zerwes** [comment]
Sorry, my decision **not** to use the LGPL
