### ISSUE TITLE
Unexpected behaviour with mapping nested in a sequence

### ISSUE THREAD

**Issue by PeteCrighton** [zerwes/hiyapyco#17]
```python
#!/usr/bin/python

import hiyapyco

test = "\n"

for a in range(1, 3):
    number_a = a
    for b in range(1, 3):
        number_b = b
        new = hiyapyco.dump([{number_a: number_b}])
        merged = hiyapyco.load(test, new, method=hiyapyco.METHOD_MERGE)
        test = hiyapyco.dump(merged, default_flow_style=False)

print(test)
```
The above script gives the output:
```yaml
- 1: 2
- 2: 1
- 2: 2
```
Whereas I would expect:
```yaml
- 1: 2
- 2: 2
```
It seems that merging only works correctly for the first sequence (I’ve tested with more than two, all subsequent behave like the second).
Is this a bug in HiYaPyCo or in my expectation? If the latter, can my desired output be achieved in another way?

_I use Python 3.5 on Arch Linux if that makes any difference._

**Comment by zerwes** [comment]
hard to say ...
I think that merging list of dicts is a mess ...
how would you merge 
`l3:
    - a: a
      b: b
    - a: A
      b: B`
and
`l3:
    - a: aaa
      c: c
    - b: BBB
      c: CCC
    - a: x
      b: y
      c: z`
?
