### ISSUE TITLE
Interpolation without converting type to string

### ISSUE THREAD

**Issue by anandtrex** [zerwes/hiyapyco#2]
First, thanks for the cool library. This is exactly what I was looking for for one of my projects. 

So one of the things I want to do in my file is to have a configuration that looks like this:
```
---
one: 1
two: 2
three: {{ one + two }}  # Doesn't work
four: "{{ two + two }}" # Works but forced into string
```

But the line containing "three" throws an exception that reads "OrderedDict not hashable". 

In Python:
```
print(conf['one'] + conf['two']) # Returns 3 as expected
print(conf['one'] + conf['four']) # TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

In your tests folder, the values are always coerced into strings. Is this a limitation of Jinja2/PyYaml? It would be great if this could be fixed, so that I get an integer/float as an interpolation of integer/floats.

Looking at the code, it seems like in HiYaPyCo._interpolate() it might make sense to assume that the value is a string if it is not any of the other types? (What are the cases where this could break?)
If you agree with this approach, I could send a pull request with the change.

**Comment by anandtrex** [comment]
After giving it some thought, and realizing that curly braces are characters with special meaning in yaml, it might make more sense to just use a different delimiter (possible by passing in the delimiter into the Jinja2 Environment creation)

**Comment by zerwes** [comment]
You are right the '{{' delimiters are the problem.
PyYAML will only accept them insight of quotes.
And the YAML cast `a: !!int {{ a + b }}` will not work as the string must first be interpolated!
I have implemented a `castinterpolated` (defaults to *False*) arg that will try to cast the interpolated string if possible (*float*, *int* or *bool*) in **0.4.1**
Give it a try.
Hope this helps.

**Comment by zerwes** [comment]
Did the {{castinterpolated}} solve your issue?
If you gained some experiences w/ different jinja delimiters you might share them here.
Regards
Klaus
