### ISSUE TITLE
Remove logging configurations code (or opt-in)

### ISSUE THREAD

**Issue by ankostis** [zerwes/hiyapyco#20]
Thank you for this super useful project.

In general, libraries should not configure logging themselves[1][2], but leave that to the driving code using them; otherwise they may overwrite pre-existing configuration.
That way issues like #9 would not even exist.

Personally I prefer not even to add a `NullHandler` suggested by the docs, and let the warning about *"uninitialized loggers"* notify client-developers that the lib is using logging which needs their attention.

In addition, the logger-name should not be configurable - if needed, client-devs can always monkeypatch module's `logger` variable.
The log-levels for various actions (`loglevelmissingfiles`) may also be left to be configured in the same way, i.e. by using 2 separate loggers, but it is not that important (no harm to the clients done).

Kind regards,
  Kostis

[1] https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library
[2] http://docs.python-guide.org/en/latest/writing/logging/#logging-in-a-library

**Comment by zerwes** [comment]
Hello Kostis.
Thank you for your feedback.
I **fully** agree with your position and this was the initial state of hiyapyco. For some stupid reason I tried to help one user complaining about the unconfigured logger warning and this was the beginning of a sad story :-/
My plans are to roll back the changes for the next release ending up in the state you suggest.
Unfortunately I am quite busy at the moment, so my decision regarding rolling back the logger stuff is still pending (same as a new release)
Hope I can manage to do this during the next days.
Kind regards
Klaus

**Comment by zerwes** [comment]
fixed in aa37baf..3e4dacb
