### ISSUE TITLE
loglevelmissingfiles ignore keyword arg

### ISSUE THREAD

**Issue by tonal** [zerwes/hiyapyco#23]
**loglevelmissingfiles** ignore keyword args an always **ERROR** or **WARNING** dependense value for **failonmissingfiles**

**Comment by zerwes** [comment]
Thank you for your report.
But please be so kind and explain me in a little bit more eloquent way the problem.
Thanks
Klaus

**Comment by tonal** [comment]
```python
>>> import logging
>>> import hiyapyco
>>> conf = hiyapyco.load(
...     'main_config.yaml', 'no_present_config.yaml',
...     failonmissingfiles=False, loglevelmissingfiles=logging.INFO)
WARNING	[hiyapyco] __init__: [Errno 2] No such file or directory: '/home/tonal/lang/python/hiyapyco/no_present_config.yaml'
WARNING	[hiyapyco] __init__: file not found: no_present_config.yaml (/home/tonal/lang/python//hiyapyco/no_present_config.yaml)
```
Bat I wait **INFO** level for message absent file.
if line https://github.com/zerwes/hiyapyco/blob/master/hiyapyco/__init__.py#L144
change to
```python
            self.loglevelonmissingfiles = kwargs.get('loglevelmissingfiles', logging.WARN)
```
All work as wait.
