### ISSUE TITLE
ResourceWarning: unclosed file in __init__.py

### ISSUE THREAD

**Issue by lesiak** [zerwes/hiyapyco#28]
Loading a file via hiyapyco results in a warning:
```
__init__.py:186: ResourceWarning: unclosed file <_io.TextIOWrapper name='PATH_TO_FILE.yaml' mode='r' encoding='cp1250'>
  f = open(fn, 'r')
```

The file is not explicitly closed.
Use `python.exe -Wall` if the warning is not enabled by default in your environment

**Comment by lesiak** [comment]
Created pull request:
https://github.com/zerwes/hiyapyco/pull/29

**Comment by zerwes** [comment]
pull request #29 accepted, merged and release
