### ISSUE TITLE
Incorrect utf-8 handling under Python3

### ISSUE THREAD

**Issue by lesiak** [zerwes/hiyapyco#30]
When reading from a file in Python 3, default file encoding is platform dependent (whatever locale.getpreferredencoding() returns)
https://docs.python.org/3.7/library/functions.html#open

There is a test case provided `test_interpolationunicode`, but I believe it is too weak.
It only tests German characters, which may pass silently on machines with German locale.

On my machine with cp1250 locale, on Python 3, loaded yaml:
- has German characters incorrectly interpreted
- parsing fails with `UnicodeDecodeError` on East-Asian characters

Same setup works fine on Python2

**Comment by lesiak** [comment]
Added pull request:
https://github.com/zerwes/hiyapyco/pull/31

**Comment by zerwes** [comment]
pull request #31 accepted, merged and released
