### ISSUE TITLE
How do you specify jinja variables in yaml files for interpolation?

### ISSUE THREAD

**Issue by inktrap** [zerwes/hiyapyco#43]
Could you please provide an example how this works? I [searched](https://github.com/zerwes/hiyapyco/search?q=interpolation) for one but couldn't find it.

What if I just want to use interpolation and don't have any yaml stuff to merge, just to place jinja placeholders in yaml values?
Wouldn't it be better to de-couple this? As it is now I would have to create the object perhaps set some attributes, and then call the internal ``_interpolate`` [method](https://github.com/zerwes/hiyapyco/blob/448e8561894794a3bf66906759a315f34aa1750d/hiyapyco/__init__.py#L269).

**Comment by zerwes** [comment]
Hi @inktrap 
No need for extra voodoo (and esp.no need for calling internal methods, as these can change at any time ...).
The lib can handle a single input without merging and interpolate jinja vars regardless of the  number of input sources ...
```syntax=python
>>> import hiyapyco
>>> yaml = """
... a: element A
... b: element B
... c: you have to say {{ b }} after {{ a }}
... """
>>> conf = hiyapyco.load(yaml, interpolate=True)
>>> print(conf)
OrderedDict([('a', 'element A'), ('b', 'element B'), ('c', 'you have to say element B after element A')])
>>> import pprint
>>> pprint.pp(conf)
OrderedDict([('a', 'element A'),
             ('b', 'element B'),
             ('c', 'you have to say element B after element A')])
```
Same approach works with files:
```syntax=python
>>> conf = hiyapyco.load('/tmp/abc.yml', interpolate=True)
>>> pprint.pp(conf)
OrderedDict([('a', 'element A'),
             ('b', 'element B'),
             ('c', 'you have to say element B after element A')])
```
Hope this helps
Greetings
Klaus

**Comment by zerwes** [comment]
btw: have a look in the examples and test dir, there you can find some examples using the jinja2 interpolation

**Comment by inktrap** [comment]
Hi @Klaus :) thanks for the clarification!

In the end, I want to do cross-document variable interpolation without merging,
which is just another way of saying that i wanted to replace jinja variables by reading their values from yaml.

Like so:

```
vars.yml
```

```
a: element A
b: element B
```

While this is a yaml file, it is also a jinja template.

```
target.yaml
```

```
c: you have to say {{ b }} after {{ a }}
```

Then this worked:

```
index.py
```

```
#!/usr/bin/env python3
import jinja2
import hiyapyco

conf = hiyapyco.load("vars.yaml", interpolate=True)
print(conf)

templateLoader = jinja2.FileSystemLoader(searchpath="./")
templateEnv = jinja2.Environment(loader=templateLoader)
TEMPLATE_FILE = "target.yaml"
template = templateEnv.get_template(TEMPLATE_FILE)
outputText = template.render(conf)  # this is where to put args to the template renderer

print(outputText)
```

I don't know if the demand for this use case is there, and if it makes sense to add some public methods for this.
Independetly of that I would be advocating to offer some additional public method, like ``merge`` to be able to use ``load`` and ``merge`` independently. Something like this:

 - ``load_yaml()`` loads a yaml file
 - ``merge_yaml()`` merges two or more yaml files
 - ``interpolate_yaml()`` just interpolates
 
That way one could:

 - load, then interpolate 
 - load multiple files and decide when to interpolate (never, before or after the merge)
 - distinguish load, merging and interpolation errors better, because they would be seperate steps
 - implement convenience functions easily, based on the functions above, for backwards compatibility.

**Comment by zerwes** [comment]
Hello @inktrap 
I think the stuff you like to realize is out of the scope of this lib.
I can just encourage you to create a open source lib [ called pyjama (python jinja machine) or something similar :-) ] that has input stream for reading vars from different sources (yaml, json, ini style conf, ...) and a jinja2 output stream that has some configurable options regarding the interpolation.
As long as it is opensource and it will be of some help for you, fell free to use some code lines from hiyapyco.
If you start that, just point me a link to the project if you like.
I am quite occupied at the moment, but who knows, maybe I can contribute something.
Have fun with your project
Greetings
Klaus

**Comment by zerwes** [comment]
@inktrap : just another note: if your purpose is just the creation of a few yaml files w/ interpolated jinja2 vars, maybe you just can use ansible w/ some tasks like this (just a excerpt from one of my firewall playbooks as a idea):
```syntax=yaml
- name: Generate auto fw rules from vlan definition
  delegate_to: localhost
  template:
    src: fw.rules.j2
    dest: "{{ auto_rules_cfg_file }}"
  when:
    - vlans is defined
    - vlans|length > 0

- name: Include auto fw rules from vlan definition
  include_vars:
    file: "{{ auto_rules_cfg_file }}"
  when:
    - vlans is defined
    - vlans|length > 0

- name: Generate volatile config
  delegate_to: localhost
  template:
    src: fw.vars.j2
    dest: "{{ tmp_var_cfg_file }}"

- name: Include volatile config
  include_vars:
    file: "{{ tmp_var_cfg_file }}"
```

**Comment by inktrap** [comment]
Hey @zerwes thanks for all the input and the suggestions :)

Maybe I am going to write such a library at some point ;P currently I am happy with the solution I outlined above. One drawback is that all placeholders get evaluated even if their variables are not defined -- which means I'll loose the ability to interpolate a second time. But that's fine.

That there are parallels between my usecase and ansible is not a coincidence … I am writing a small framework to configure openwrt via fabric and the config is stored declaratively in yaml files. It will rely only on ssh and won't need python or a patched ``uci`` or something.

If you can come up with a nice name for that (I like pyjama a lot), I'll be happy hear it. Currently idea is funsible ;P

**Comment by zerwes** [comment]
> One drawback is that all placeholders get evaluated even if their variables are not defined -- which means I'll loose the ability to interpolate a second time

https://github.com/zerwes/hiyapyco#change-the-jinja2-environment

Ah sounds like a lot of fun :-) I do not use openwrt (anymore). But I struggle w/ opnsense:
 https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense
