### ISSUE TITLE
release pr  #42

### ISSUE THREAD

**Issue by zerwes** [zerwes/hiyapyco#44]
make a new release including  #42
in the worst case: drop python 2.7 support

**Comment by M-Bab** [comment]
Hello @zerwes ! What is the release plan for 0.4.17? I would be really glad when the jinja2 issue is fixed. This works already when I install hiyapyco from github but its simply not available from pip/pypy so far.

Or can I help in any way to get this fix released?

**Comment by zerwes** [comment]
Finally release 0.5.0 is out.
https://pypi.org/project/HiYaPyCo/0.5.0/

Sorry for the delay!
There where several issues with the build and release steps.
So I had to drop python 2 support to get this all working again.
Due to the major change of sunsetting python 2 support, I decided to use a new (minor) release number.
