### ISSUE TITLE
List Items order matters?

### ISSUE THREAD

**Issue by fabriziowho** [zerwes/hiyapyco#48]
Hello there,
first of all, thank you for your availability. I've recently played with hiyapyco and I discovered a strange behavior using nested lists inside YAML files. The goal is to overwrite the list values with the latest ones.

**Issue**
I ran the snippet below and hiyapyco detects different values and merges all of them. Here below the snippet to replicate the issue:

```
import hiyapyco
base = """deploy:
  strategy: RollingUpdate
  maxSurge: 2
  maxUnavailable: 1
  env:
    - CORECLR_ENABLE_PROFILING: 0
    - DD_ENV: development
"""
shared = """deploy:
  strategy: RollingUpdate
  maxSurge: 5
  maxUnavailable: 1
  env:
    - CORECLR_ENABLE_PROFILING: 0
    - DD_ENV: stage
"""
develop = """deploy:
  strategy: RollingUpdate
  maxSurge: 2
  maxUnavailable: 1
  env:
    - DD_ENV: production
    - CORECLR_ENABLE_PROFILING: 1
"""
merged_yaml = hiyapyco.load([base, shared, develop], method=hiyapyco.METHOD_MERGE, interpolate=False, failonmissingfiles=True)
print(hiyapyco.dump(merged_yaml))
```

**Test 1 Result**
```
>>> python3 test-merge2.py
deploy:
  strategy: RollingUpdate
  maxSurge: 2
  maxUnavailable: 1
  env:
  - CORECLR_ENABLE_PROFILING: 0
  - DD_ENV: stage
  - DD_ENV: production
  - CORECLR_ENABLE_PROFILING: 1
```

**Workaround**
I changed the order of the list items and used the same order in the list in each file (f.i. in develop, 1st CORECLR_ENABLE_PROFILING: 1, 2nd DD_ENV: production), below is the result:

**Test 2 Result**
```
>>> python3 test-merge2.py
deploy:
  strategy: RollingUpdate
  maxSurge: 2
  maxUnavailable: 1
  env:
  - CORECLR_ENABLE_PROFILING: 1
  - DD_ENV: production
```

Is it should work like that? Do the list items have to be in the same position in each file?

Many Thanks,
Fabrizio

**Comment by zerwes** [comment]
Hello @fabriziowho. Sorry for the delay. Glad to see you resolved this for you.
Just a final note: list merging is somehow tricky (probably the reason why this is often omitted completely for example in the puppet hiera and ansible merge strategies)  ... I have tried to cover some cases (see: https://github.com/zerwes/hiyapyco/blob/master/hiyapyco/__init__.py#L403:L438) esp. if the list items are dicts.
And there are some cfg args regarding this:
 * `mergelists` as bool
 * the (unsupported) hiyapyco.METHOD_SUBSTITUTE
If you feel this is incomplete, just let me know...
And by the way: PRs are welcome (wit a test scenario included)
