### ISSUE TITLE
ansible !vault variable not load

### ISSUE THREAD

**Issue by artb1sh** [zerwes/hiyapyco#49]
if parse ansible-vault variable
```
my_encrypted_var: !vault |
          $ANSIBLE_VAULT;1.2;AES256;dev
          30613233633461343837653833666333643061636561303338373661313838333565653635353162
          3263363434623733343538653462613064333634333464660a663633623939393439316636633863
          61636237636537333938306331383339353265363239643939666639386530626330633337633833
          6664656334373166630a363736393262666465663432613932613036303963343263623137386239
          6330
```

yaml.constructor.ConstructoError: Could not determine a constructor for the tag "!vault"

**Comment by zerwes** [comment]
This is `hiyapyco`, not `ansible`, so why do you assume that the ansible vault will be loaded?
If you need this, there must be 2 changes:
 1. hiyapyco needs to be extended to allow you to use a self defined yaml class https://github.com/zerwes/hiyapyco/blob/4527b004ead042551b3f959c9fbbc07faf6bba62/hiyapyco/__init__.py#L234
 2.  you need to write a extension of the default yaml class that will handle the vault (https://pyyaml.docsforge.com/master/api/yaml/add_constructor/) and then use this as mentioned in the first point.

So if you feel this is really something you want to do, please open a PR or at least a issue with the corresponding correct topic.
But for now: sorry, and once more: this is `hiyapyco`, not `ansible`, therefore **wontfix**
