### ISSUE TITLE
how add !vault tag

### ISSUE THREAD

**Issue by artb1sh** [zerwes/hiyapyco#50]
how add !vault tag

**Comment by artb1sh** [comment]
i need tag for merge ansible variables

**Comment by zerwes** [comment]
Hello @artb1sh 
Please have a look at the [example script](/zerwes/hiyapyco/tree/master/examples/tags.py) for the [sample yaml](/zerwes/hiyapyco/tree/master/examples/tags.yaml).
This should preserve your tags (not evaluating them, so you can pass the result later to ansible).
Currently it is just working with the default yaml loader, not the [ordered dict yaml loader](https://github.com/zerwes/hiyapyco#ordered-dict-yaml-loader--dumper-aka-odyldo).

Just let me know if this fits your needs ...

BTW: is there a reason not using ansibles `hash_behaviour = merge` ? (https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-hash-behaviour)

**Comment by zerwes** [comment]
FYI: you can find more yaml voodoo at https://pyyaml.docsforge.com/master/api/

**Comment by zerwes** [comment]
@artb1sh glad to hear it helps

> your code snippet works 20 times faster than Ansible.

I assume this is **not** due to the *quick & dirty* code quality of my code :-) but caused by the different scope of the tools ... I *use* ansible, I do no competition with it :-)

**Comment by artb1sh** [comment]
@zerwes I use this as a quick addon for validating all ansible jinja variables
1. hiyapyco merge variable 
2. render jinja template script
if good to
3. ansible start
ansible check very slow

**Comment by zerwes** [comment]
> I use this as a quick addon for validating all ansible jinja variables

OK, I understand. Just keep in mind that ansible and hiyapyco use different list merging strategies:
ansible will newer merge lists, but hiyapyco will do this sometimes.

```
# hosts
[testgroup]
testhost ansible_connection=local
```
```yaml
# group_vars/testgroup.yml
---
tlist:
  - x
  - y
  - z
```
```yaml
# host_vars/testhost.yml
---
tlist:
  - a
  - b
  - c
```
```yaml
# list.yml
---
- name: list merge
  hosts: testgroup
  gather_facts: false
  tasks:
    - debug:
        var: tlist
```
=>
```
$ ANSIBLE_HASH_BEHAVIOUR=merge ansible-playbook -i hosts list.yml 

PLAY [list merge] ***********************************************************************************************************************************************************

TASK [debug] ****************************************************************************************************************************************************************
ok: [testhost] => {
    "tlist": [
        "a",
        "b",
        "c"
    ]
}

PLAY RECAP ******************************************************************************************************************************************************************
testhost                   : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

```python
#! /usr/bin/env python
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4 smartindent nu

import sys
import os
import hiyapyco

basepath = os.path.dirname(os.path.realpath(__file__))

print('='*10, 'method=hiyapyco.METHOD_SIMPLE', '='*10)
conf = hiyapyco.load(
        os.path.join(basepath, 'group_vars/testgroup.yml'),
        os.path.join(basepath, 'host_vars/testhost.yml'),
        method=hiyapyco.METHOD_SIMPLE,
        failonmissingfiles=True
        )
print(conf)
print('-'*10, 'YAML', '-'*10)
print(hiyapyco.dump(conf))

print('='*10, 'method=hiyapyco.METHOD_MERGE', '='*10)
conf = hiyapyco.load(
        os.path.join(basepath, 'group_vars/testgroup.yml'),
        os.path.join(basepath, 'host_vars/testhost.yml'),
        method=hiyapyco.METHOD_MERGE,
        failonmissingfiles=True
        )
print(conf)
print('-'*10, 'YAML', '-'*10)
print(hiyapyco.dump(conf))
```
=>
```
========== method=hiyapyco.METHOD_SIMPLE ==========
OrderedDict([('tlist', ['a', 'b', 'c'])])
---------- YAML ----------
tlist:
- a
- b
- c

========== method=hiyapyco.METHOD_MERGE ==========
OrderedDict([('tlist', ['x', 'y', 'z', 'a', 'b', 'c'])])
---------- YAML ----------
tlist:
- x
- y
- z
- a
- b
- c
```

Anyhow: glad I could help
