### ISSUE TITLE
import of hiyapyco __version__ in setup.py causes pip install failures

### ISSUE THREAD

**Issue by dmbryson** [zerwes/hiyapyco#6]
Importing hiyapyco in setup.py causes pip install failures when PyYAML (and Jinja2) have not previously been installed in a virtualenv. 

<excerpt>
Collecting PyYAML==3.11 (from ...)
  Using cached PyYAML-3.11.tar.gz
Collecting HiYaPyCo==0.4.1 (from ...)
  Using cached HiYaPyCo-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/f7/js66bsc95mq6qp9b178zvngr0000gq/T/pip-build-oyKfvh/HiYaPyCo/setup.py", line 10, in <module>
        from hiyapyco import __version__ as hiyapycoversion
      File "hiyapyco/__init__.py", line 24, in <module>
        import yaml
    ImportError: No module named yaml
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/f7/js66bsc95mq6qp9b178zvngr0000gq/T/pip-build-oyKfvh/HiYaPyCo
</excerpt>

**Comment by zerwes** [comment]
thx for the hint
should be fixed w/ release 0.4.3
