### ISSUE TITLE
OrderedDict loader

### ISSUE THREAD

**Issue by grst** [zerwes/hiyapyco#73]
Hi, 

great tool! I have a question about the YAML loader:

Since Python 3.7, [dictionaries are ordered by default](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6). Is there still any benefit from using the OrderedDict loader coming with hiyapyco?

**Comment by zerwes** [comment]
Hello @grst 
good question  :-)
as the implementations differ, I would say : "_it depends_"

If you started your project before 3.7 and used the default `usedefaultyamlloader=False`, I would recommend leaving it this way.
If you start a new project, you can start with `usedefaultyamlloader=True`!
To be honest, my own OrderedDict loader aka. `odyldo` was some kind of q&d solution.
But changing defaults will somewhere break things, so I will not change this, but feel free to preferably trust the upstream python implementation more than the somewhere obscure `odyldo` :-)

see the example in commit b25ab4fab48d13d19ee9a1ecdc11fe7f6f2d6a17
```
± ./examples/issue73compareOrderedDict.py -f examples/issue73compareOrderedDict.yml
========== usedefaultyamlloader= True ==========
{'ooo': 'xyz', 'llll': {'a': 'A', 'z': 'Z', 'b': 'B'}, 'aaa': 'first'}
---------- YAML ----------
aaa: first
llll:
  a: A
  b: B
  z: Z
ooo: xyz

========== usedefaultyamlloader= False ==========
OrderedDict([('ooo', 'xyz'), ('llll', OrderedDict([('a', 'A'), ('z', 'Z'), ('b', 'B')])), ('aaa', 'first')])
---------- YAML ----------
ooo: xyz
llll:
  a: A
  z: Z
  b: B
aaa: first
```

**Comment by grst** [comment]
Thanks for answering, that makes sense!
