### ISSUE TITLE
Using a custom yaml loader class

### ISSUE THREAD

**Issue by grst** [zerwes/hiyapyco#74]
It would be nice if I could pass a custom callback function for parsing yaml files. 
There's already support for the native yaml loader and the OrderedDict yaml loader and there is a feature branch with support for `ruamel`. Instead of special-casing the different loaders, there could be an argument to the `hiyapyco` function that takes a callback function/loader class. 

My use case is that I would like to enable "unsafe" loading of some `!objects`, therefore I'd need a custom loader instead of using `safe_load`.

**Comment by zerwes** [comment]
Hello @grst 
Sounds similar to #68 ...
Well, I can understand the need for this, but I have to admit: I simply don’t have the time for it at the moment ...
To give a broad hint: PR are welcome :-/
