### ISSUE TITLE
Interpolation fails when using custom yaml objects

### ISSUE THREAD

**Issue by grst** [zerwes/hiyapyco#79]
I am working with yaml files that have custom objects using the yaml `!tag`  feature that I read in using a custom yaml loader function (see #77). 

This works well, but is incompatibe with the Jinja2 interpolation feature, because it hits the `HiYaPyCoImplementationException` in `_interpolate`: 

https://github.com/zerwes/hiyapyco/blob/faf760664f2daa308551a56488780515ff7508a0/hiyapyco/__init__.py#L284-L300

A possible solution would be to return objects of unknown type unchanged instead of raising an exception. IMO this could be the default, but it could also be made configurable to switch between current behavior (raise an exception) and alternative behavior (ignore objects of unknown type). 

LMK if you'd accept a PR in that direction. 

Cheers, 
Gregor

**Comment by zerwes** [comment]
I am currently on vacation and will take care of it when I get back ...

**Comment by zerwes** [comment]
Hello @grst 
A PR that preserves the default behavior but gives the user the option to _return objects of unknown type unchanged_ seems a good option.
PRs that extend the functionality while preserving the default behavior are **always welcome**, as long as the intended usage is not to exotic and might be of use for other users.

**Comment by grst** [comment]
I think I found a better way, but just letting my custom class inherit from one of the base types (e.g. `str`). 

Therefore, closing this for now.
